# Minecraft 26.1.2 sudah unobfuscated -> tidak pakai Yarn lagi, tapi mapping resmi Mojang.
minecraft_version=26.1.2

# Cek versi terbaru/pasti di https://fabricmc.net/develop (kombinasi loader/loom/api untuk 26.1.x)
loader_version=0.18.4
fabric_version=0.146.1+26.1.2

# Info mod
mod_version=1.0.0
maven_group=com.qayza
archives_base_name=bellrange

org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
